# Generated by Django 3.2.15 on 2023-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Room_Rate', models.IntegerField(blank=True, default='0', null=True)),
                ('Room_Image', models.ImageField(blank=True, null=True, upload_to='Room')),
            ],
        ),
    ]
